### ISSUE TITLE
User can't add additional liquidity

### ISSUE THREAD

**Issue by bthaile** [AugurProject/turbo#269]
estimate to add additional liquidity works but the MM gas estimate blows up. 

![image](https://user-images.githubusercontent.com/3970376/115569065-7fe38f00-a282-11eb-8a00-4bc2025ddd29.png)

**Comment by Chwy5** [comment]
still an issue

**Comment by bthaile** [comment]
I think this is fixed.

**Comment by Chwy5** [comment]
Still an issue on games where all the liquidity has been removed...

Getting this error..

![image](https://user-images.githubusercontent.com/41301809/118358013-e8a0ed00-b54a-11eb-949e-dd057c4b6f06.png)

**Comment by justinbarry** [comment]
Closed by #522
